shape: [4, 12]
stochasticity: none
reward_cliff: -100
reward_step: -1
wind_prob: 0.0
timesteps: 350000
n_eval_episodes: 4
lr: 0.0001
gamma: 0.99
batch_size: 8
entropy_coef: 0.5
entropy_coef_final: 0.01
n_seeds: 1
